# Generated by Django 5.1.2 on 2024-10-19 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='chatbox',
            new_name='chatroom',
        ),
    ]
